disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Makenthor"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
# logo = "img/logo.png"
# secondaryLogo = "img/secondary-logo.png"
#   description = "My awesome website"
copyright = "&copy; 2025 Makenthor. All Rights Reserved."

[params.author]
name = "Makenthor"
email = "makenthor.lab@gmail.com"
image = "https://avatars.githubusercontent.com/u/210733978?v=4"
imageQuality = 96
headline = "Learning Nerd | IT & Electronics FanBoy"
bio = ""
links = [
  { email = "mailto:makenthor.lab@gmail.com" },
  #     { link = "https://link-to-some-website.com/" },
  #     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #     { apple = "https://www.apple.com" },
  #     { blogger = "https://username.blogspot.com/" },
  #     { bluesky = "https://bsky.app/profile/username" },
  #     { codepen = "https://codepen.io/username" },
  #     { dev = "https://dev.to/username" },
  { discord = "https://discord.gg/EababZFm" },
  #     { dribbble = "https://dribbble.com/username" },
  #     { facebook = "https://facebook.com/username" },
  #     { flickr = "https://www.flickr.com/photos/username/" },
  #     { foursquare = "https://foursquare.com/username" },
  { github = "https://github.com/Makenthor" },
  #     { gitlab = "https://gitlab.com/username" },
  #     { google = "https://www.google.com/" },
  #     { hashnode = "https://username.hashnode.dev" },
  { instagram = "https://instagram.com/makenthor.lab" },
  #     { itch-io = "https://username.itch.io" },
  #     { keybase = "https://keybase.io/username" },
  #     { keyoxide = "https://keyoxide.org/URI" },
  #     { kickstarter = "https://www.kickstarter.com/profile/username" },
  #     { lastfm = "https://lastfm.com/user/username" },
  #     { linkedin = "https://linkedin.com/in/username" },
  #     { mastodon = "https://mastodon.instance/@username" },
  #     { matrix = "https://matrix.to/#/URI" },
  #     { medium = "https://medium.com/username" },
  #     { microsoft = "https://www.microsoft.com/" },
  #     { orcid = "https://orcid.org/userid" },
  #     { patreon = "https://www.patreon.com/username" },
  #     { pinterest = "https://pinterest.com/username" },
  #     { reddit = "https://reddit.com/user/username" },
  #     { researchgate = "https://www.researchgate.net/profile/username" },
  #     { signal = "https://signal.me/#eu/userid" },
  #     { slack = "https://workspace.url/team/userid" },
  #     { snapchat = "https://snapchat.com/add/username" },
  #     { soundcloud = "https://soundcloud.com/username" },
  { spotify = "https://open.spotify.com/playlist/4h0NfXoNEyS5FEl7WF0F1R?si=18b45d1a2cfe4bc4" },
  #     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #     { steam = "https://steamcommunity.com/profiles/userid" },
  #     { telegram = "https://t.me/username" },
  #     { threads = "https://www.threads.net/@username" },
  #     { tiktok = "https://tiktok.com/@username" },
  #     { tumblr = "https://username.tumblr.com" },
  #     { twitch = "https://twitch.tv/username" },
  #     { twitter = "https://twitter.com/username" },
  #     { x-twitter = "https://twitter.com/username" },
  #     { whatsapp = "https://wa.me/phone-number" },
  { youtube = "https://www.youtube.com/@makenthor_lab?sub_confirmation=1" },
  #     { ko-fi = "https://ko-fi.com/username" },
  #     { codeberg = "https://codeberg.org/username"},
]
